In [1]:
import cv2
import random
import numpy as np
from matplotlib import pyplot as plt

In [3]:
img = cv2.imread('face.jpg')

In [4]:
print (img)

[[[22 30 47]
  [20 30 47]
  [20 30 47]
  ...
  [ 3  5  6]
  [ 2  4  5]
  [ 2  4  5]]

 [[22 32 49]
  [22 32 49]
  [22 32 49]
  ...
  [ 3  5  6]
  [ 2  4  5]
  [ 2  4  5]]

 [[24 34 51]
  [24 34 51]
  [25 35 52]
  ...
  [ 3  5  6]
  [ 3  5  6]
  [ 2  4  5]]

 ...

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]]


In [5]:
cv2.imshow('face',img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [21]:
# image crope
img_crop = img [100:200,30:250]

In [22]:
cv2.imshow('face',img_crop)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [23]:
print(img_crop)

[[[  0   2   6]
  [ 10  12  13]
  [  2  10  17]
  ...
  [ 19  34  50]
  [ 17  32  48]
  [ 15  30  46]]

 [[  0   3   7]
  [  5   7   8]
  [  1  10  14]
  ...
  [ 19  34  50]
  [ 17  32  48]
  [ 16  31  47]]

 [[  2   5   9]
  [  3   5   6]
  [  2   8  13]
  ...
  [ 20  35  51]
  [ 18  33  49]
  [ 16  31  47]]

 ...

 [[ 82 111 142]
  [ 82 113 146]
  [ 92 120 154]
  ...
  [ 16  31  47]
  [ 14  29  45]
  [ 13  28  44]]

 [[ 83 113 142]
  [ 85 115 144]
  [ 90 118 153]
  ...
  [ 16  31  47]
  [ 14  29  45]
  [ 12  27  43]]

 [[ 84 113 140]
  [ 86 115 142]
  [ 87 115 150]
  ...
  [ 15  30  46]
  [ 14  29  45]
  [ 12  27  43]]]


In [24]:
#image color
B , G , R = cv2.split(img)

In [27]:
print( B , G , R )

[[22 20 20 ...  3  2  2]
 [22 22 22 ...  3  2  2]
 [24 24 25 ...  3  3  2]
 ...
 [ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]] [[30 30 30 ...  5  4  4]
 [32 32 32 ...  5  4  4]
 [34 34 35 ...  5  5  4]
 ...
 [ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]] [[47 47 47 ...  6  5  5]
 [49 49 49 ...  6  5  5]
 [51 51 52 ...  6  6  5]
 ...
 [ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]]


In [ ]:
def random_light_color(img):
    # birghtness
    B , G ,R = cv2.split(img)
    
    # change  B channel
    b_rand = random.randint(-50, 50)
    if b_rand == 0:
        pass
    elif b_rand > 0:
        lim = 255 - b_rand
        B[B > lim] =255
        B[B <= lim] = (b_rand + B[B <= lim]).astype(img.dtype) #astype
    elif b_rand < 0:
        lim = 0 - b_rand
        B[B >= lim] = (b_rand + B[B >= lim]).astype(img.dtype)
    
    # change G channel 
    g_rand = random.randint(-50, 50)
    if g_rand == 0:
        pass
    elif g_rand > 0:
        lim = 255 - g_rand
        G[G > lim] =255
        G[G <= lim] = (g_rand + G[G <= lim]).astype(img.dtype) #astype
    elif g_rand < 0:
        lim = 0 - g_rand
        G[G >= lim] = (g_rand + G[G >= lim]).astype(img.dtype)
        
       # change R channel 
    r_rand = random.randint(-50, 50)
    if r_rand == 0:
        pass
    elif r_rand > 0:
        lim = 255 - r_rand
        R[R > lim] =255
        R[R <= lim] = (r_rand + R[R <= lim]).astype(img.dtype) #astype
    elif r_rand < 0:
        lim = 0 - r_rand
        R[R >= lim] = (r_rand + R[R >= lim]).astype(img.dtype)
        
        img_merge = cv2.merge((B, G, R)) #merge 合并图像
        return img_merge
        